FROM postgres:15.7-bookworm as plv8

ENV PLV8_VERSION=3.1.10 PG_MAJOR=15

RUN --mount=type=cache,target=/var/cache/apt \
    buildDependencies="build-essential \
    postgresql-$PG_MAJOR \
    ca-certificates \
    curl \
    wget \
    git-core \
    gnupg \
    gpp \
    cpp \
    pkg-config \
    apt-transport-https \
    cmake \
    libc++1 \
    libc++-dev \
    libncurses5 \
    libc++abi-dev \
    zlib1g-dev \
    ninja-build \
    postgresql-server-dev-$PG_MAJOR" \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${buildDependencies}

RUN mkdir -p /tmp/build \
  && curl -o /tmp/build/v$PLV8_VERSION.tar.gz -SL "https://github.com/plv8/plv8/archive/refs/tags/v${PLV8_VERSION}.tar.gz" \
  && cd /tmp/build \
  && tar -xzf /tmp/build/v$PLV8_VERSION.tar.gz -C /tmp/build/ \
  && cd /tmp/build/plv8-$PLV8_VERSION \
  && make static \
  && make install \
  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so \
  && rm -fr /tmp/build

FROM postgres:15.7-bookworm
RUN mkdir -p /usr/lib/postgresql/${PG_MAJOR}/lib/
ENV PLV8_VERSION=3.1.10
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg2 libc++1
COPY --from=plv8 /usr/share/postgresql/${PG_MAJOR}/extension/ /usr/share/postgresql/${PG_MAJOR}/extension/
COPY --from=plv8 /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so
