FROM postgres:16-bookworm as plv8

ENV PLV8_BRANCH=v3.2.2 PLV8_VERSION=3.2.2 PG_MAJOR=16

RUN --mount=type=cache,target=/var/cache/apt \
    buildDependencies="build-essential \
    postgresql-$PG_MAJOR \
    ca-certificates \
    git-core \
    gnupg \
    gpp \
    cpp \
    pkg-config \
    apt-transport-https \
    cmake \
    libc++1 \
    libc++-dev \
    libstdc++-12-dev \
    libncurses5 \
    libc++abi-dev \
    libtinfo5 \
	  zlib1g-dev \
	  ninja-build \
    postgresql-server-dev-$PG_MAJOR" \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${buildDependencies}

RUN mkdir -p /tmp/build \
  && cd /tmp/build \
  && set -ex \
  && git clone --branch ${PLV8_BRANCH} --single-branch --depth 1 https://github.com/plv8/plv8 \
  && cd plv8 \
  && make \
  && make install \
  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so \
  && rm -fr /tmp/build

FROM postgres:16-bookworm
RUN mkdir -p /usr/lib/postgresql/${PG_MAJOR}/lib/
ENV PLV8_VERSION=3.2.2
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg2 libc++1
COPY --from=plv8 /usr/share/postgresql/${PG_MAJOR}/extension/ /usr/share/postgresql/${PG_MAJOR}/extension/
COPY --from=plv8 /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so
